"""init_schema_completo

Revision ID: 038c1f341d45
Revises: 
Create Date: 2026-07-26 11:11:48.839692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '038c1f341d45'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_motivos_parada',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_parada', sa.Enum('PLANIFICADA', 'NO_PLANIFICADA', name='tipoparada'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_motivos_parada_tenant_id'), 'dim_motivos_parada', ['tenant_id'], unique=False)
    op.create_table('dim_operarios',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('legajo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_operarios_legajo'), 'dim_operarios', ['legajo'], unique=False)
    op.create_index(op.f('ix_dim_operarios_tenant_id'), 'dim_operarios', ['tenant_id'], unique=False)
    op.create_table('dim_supervisores',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('legajo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre_completo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_supervisores_legajo'), 'dim_supervisores', ['legajo'], unique=False)
    op.create_index(op.f('ix_dim_supervisores_tenant_id'), 'dim_supervisores', ['tenant_id'], unique=False)
    op.create_table('eventos_plc_ciclos',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('maquina_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('formato_moldes', sa.Integer(), nullable=False),
    sa.Column('panes_producidos', sa.Integer(), nullable=False),
    sa.Column('delta_tiempo_s', sa.Float(), nullable=False),
    sa.Column('categoria_parada', sa.Enum('NORMAL', 'MICRO_MENOR', 'MICRO_MAYOR', name='categoriaparada'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_plc_ciclos_categoria_parada'), 'eventos_plc_ciclos', ['categoria_parada'], unique=False)
    op.create_index(op.f('ix_eventos_plc_ciclos_maquina_id'), 'eventos_plc_ciclos', ['maquina_id'], unique=False)
    op.create_index(op.f('ix_eventos_plc_ciclos_tenant_id'), 'eventos_plc_ciclos', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_eventos_plc_ciclos_timestamp'), 'eventos_plc_ciclos', ['timestamp'], unique=False)
    op.create_table('lite_eventos_produccion',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('id_estacion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_pieza', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('orden_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cantidad_producida', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('delta_t_segundos', sa.Float(), nullable=False),
    sa.Column('estado', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('es_parada_detectada', sa.Boolean(), nullable=False),
    sa.Column('tiempo_perdido_segundos', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lite_eventos_produccion_codigo_pieza'), 'lite_eventos_produccion', ['codigo_pieza'], unique=False)
    op.create_index(op.f('ix_lite_eventos_produccion_estado'), 'lite_eventos_produccion', ['estado'], unique=False)
    op.create_index(op.f('ix_lite_eventos_produccion_id_estacion'), 'lite_eventos_produccion', ['id_estacion'], unique=False)
    op.create_index(op.f('ix_lite_eventos_produccion_orden_fk'), 'lite_eventos_produccion', ['orden_fk'], unique=False)
    op.create_index(op.f('ix_lite_eventos_produccion_tenant_id'), 'lite_eventos_produccion', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_lite_eventos_produccion_timestamp'), 'lite_eventos_produccion', ['timestamp'], unique=False)
    op.create_table('maestro_skus',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('codigo_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modelo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('medida', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tiempo_ciclo_teorico', sa.Float(), nullable=False),
    sa.Column('umbral_calidad', sa.Float(), nullable=False),
    sa.Column('unidades_por_ciclo', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('codigo_sku')
    )
    op.create_index(op.f('ix_maestro_skus_tenant_id'), 'maestro_skus', ['tenant_id'], unique=False)
    op.create_table('plantas',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ubicacion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plantas_tenant_id'), 'plantas', ['tenant_id'], unique=False)
    op.create_table('tenants_saas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_primario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locale_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_asignacion_operarios', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tolerancia_lento_pct', sa.Float(), nullable=False),
    sa.Column('tolerancia_alerta_pct', sa.Float(), nullable=False),
    sa.Column('regex_parser_orden', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('regex_parser_sku', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('origen_maestros', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios_saas',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('auth0_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rol', sa.Enum('SUPERADMIN', 'GERENCIA', 'PRODUCCION', 'SUPERVISOR', 'OPERARIO', name='rolusuario'), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('apellido', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_saas_auth0_id'), 'usuarios_saas', ['auth0_id'], unique=True)
    op.create_index(op.f('ix_usuarios_saas_tenant_id'), 'usuarios_saas', ['tenant_id'], unique=False)
    op.create_table('dim_lineas',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('planta_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('modo_asignacion_operarios', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo_produccion', sa.Enum('DISCRETA', 'POR_LOTES', name='tipoproduccion'), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['plantas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_lineas_tenant_id'), 'dim_lineas', ['tenant_id'], unique=False)
    op.create_table('dim_estaciones',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('tipo', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('umbral_optimo', sa.Integer(), nullable=False),
    sa.Column('umbral_lento', sa.Integer(), nullable=False),
    sa.Column('umbral_alerta', sa.Integer(), nullable=False),
    sa.Column('activa', sa.Boolean(), nullable=False),
    sa.Column('posicion_linea', sa.Integer(), nullable=False),
    sa.Column('ramal', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('linea_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('codigo_plc', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('modo_asignacion_operarios', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orden_activa_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sku_activo_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['linea_id'], ['dim_lineas.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['dim_estaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_estaciones_codigo_plc'), 'dim_estaciones', ['codigo_plc'], unique=False)
    op.create_index(op.f('ix_dim_estaciones_tenant_id'), 'dim_estaciones', ['tenant_id'], unique=False)
    op.create_table('dim_turnos',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fin', sa.Time(), nullable=False),
    sa.Column('descanso_minutos', sa.Integer(), nullable=False),
    sa.Column('linea_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['linea_id'], ['dim_lineas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dim_turnos_tenant_id'), 'dim_turnos', ['tenant_id'], unique=False)
    op.create_table('ordenes_produccion',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id_orden', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sku_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('linea_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('cantidad_esperada', sa.Integer(), nullable=False),
    sa.Column('cantidad_producida', sa.Integer(), nullable=False),
    sa.Column('plan_fecha', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('estado', sa.Enum('ABIERTA', 'EN_PROGRESO', 'CERRADA', name='estadoorden'), nullable=False),
    sa.Column('origen', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['linea_id'], ['dim_lineas.id'], ),
    sa.ForeignKeyConstraint(['sku_fk'], ['maestro_skus.codigo_sku'], ),
    sa.PrimaryKeyConstraint('id_orden')
    )
    op.create_index(op.f('ix_ordenes_produccion_tenant_id'), 'ordenes_produccion', ['tenant_id'], unique=False)
    op.create_table('asignaciones_turno',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('estacion_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('operario_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('turno_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_fk'], ['dim_estaciones.id'], ),
    sa.ForeignKeyConstraint(['operario_fk'], ['dim_operarios.id'], ),
    sa.ForeignKeyConstraint(['turno_fk'], ['dim_turnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asignaciones_turno_tenant_id'), 'asignaciones_turno', ['tenant_id'], unique=False)
    op.create_table('eventos_escaneo',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('barcode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('estacion_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('orden_fk', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operario_fk', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('desempeno', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('segundos_proceso', sa.Integer(), nullable=True),
    sa.Column('es_retrabajo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['estacion_fk'], ['dim_estaciones.id'], ),
    sa.ForeignKeyConstraint(['operario_fk'], ['dim_operarios.id'], ),
    sa.ForeignKeyConstraint(['orden_fk'], ['ordenes_produccion.id_orden'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eventos_escaneo_tenant_id'), 'eventos_escaneo', ['tenant_id'], unique=False)
    op.create_index('ix_tenant_barcode', 'eventos_escaneo', ['tenant_id', 'barcode'], unique=False)
    op.create_table('paradas_detectadas',
    sa.Column('tenant_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('estacion_fk', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.Column('fin', sa.DateTime(), nullable=True),
    sa.Column('duracion_segundos', sa.Float(), nullable=True),
    sa.Column('estado', sa.Enum('PENDIENTE', 'CLASIFICADA', name='estadoparada'), nullable=False),
    sa.Column('motivo_fk', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['estacion_fk'], ['dim_estaciones.id'], ),
    sa.ForeignKeyConstraint(['motivo_fk'], ['dim_motivos_parada.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paradas_detectadas_tenant_id'), 'paradas_detectadas', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_paradas_detectadas_tenant_id'), table_name='paradas_detectadas')
    op.drop_table('paradas_detectadas')
    op.drop_index('ix_tenant_barcode', table_name='eventos_escaneo')
    op.drop_index(op.f('ix_eventos_escaneo_tenant_id'), table_name='eventos_escaneo')
    op.drop_table('eventos_escaneo')
    op.drop_index(op.f('ix_asignaciones_turno_tenant_id'), table_name='asignaciones_turno')
    op.drop_table('asignaciones_turno')
    op.drop_index(op.f('ix_ordenes_produccion_tenant_id'), table_name='ordenes_produccion')
    op.drop_table('ordenes_produccion')
    op.drop_index(op.f('ix_dim_turnos_tenant_id'), table_name='dim_turnos')
    op.drop_table('dim_turnos')
    op.drop_index(op.f('ix_dim_estaciones_tenant_id'), table_name='dim_estaciones')
    op.drop_index(op.f('ix_dim_estaciones_codigo_plc'), table_name='dim_estaciones')
    op.drop_table('dim_estaciones')
    op.drop_index(op.f('ix_dim_lineas_tenant_id'), table_name='dim_lineas')
    op.drop_table('dim_lineas')
    op.drop_index(op.f('ix_usuarios_saas_tenant_id'), table_name='usuarios_saas')
    op.drop_index(op.f('ix_usuarios_saas_auth0_id'), table_name='usuarios_saas')
    op.drop_table('usuarios_saas')
    op.drop_table('tenants_saas')
    op.drop_index(op.f('ix_plantas_tenant_id'), table_name='plantas')
    op.drop_table('plantas')
    op.drop_index(op.f('ix_maestro_skus_tenant_id'), table_name='maestro_skus')
    op.drop_table('maestro_skus')
    op.drop_index(op.f('ix_lite_eventos_produccion_timestamp'), table_name='lite_eventos_produccion')
    op.drop_index(op.f('ix_lite_eventos_produccion_tenant_id'), table_name='lite_eventos_produccion')
    op.drop_index(op.f('ix_lite_eventos_produccion_orden_fk'), table_name='lite_eventos_produccion')
    op.drop_index(op.f('ix_lite_eventos_produccion_id_estacion'), table_name='lite_eventos_produccion')
    op.drop_index(op.f('ix_lite_eventos_produccion_estado'), table_name='lite_eventos_produccion')
    op.drop_index(op.f('ix_lite_eventos_produccion_codigo_pieza'), table_name='lite_eventos_produccion')
    op.drop_table('lite_eventos_produccion')
    op.drop_index(op.f('ix_eventos_plc_ciclos_timestamp'), table_name='eventos_plc_ciclos')
    op.drop_index(op.f('ix_eventos_plc_ciclos_tenant_id'), table_name='eventos_plc_ciclos')
    op.drop_index(op.f('ix_eventos_plc_ciclos_maquina_id'), table_name='eventos_plc_ciclos')
    op.drop_index(op.f('ix_eventos_plc_ciclos_categoria_parada'), table_name='eventos_plc_ciclos')
    op.drop_table('eventos_plc_ciclos')
    op.drop_index(op.f('ix_dim_supervisores_tenant_id'), table_name='dim_supervisores')
    op.drop_index(op.f('ix_dim_supervisores_legajo'), table_name='dim_supervisores')
    op.drop_table('dim_supervisores')
    op.drop_index(op.f('ix_dim_operarios_tenant_id'), table_name='dim_operarios')
    op.drop_index(op.f('ix_dim_operarios_legajo'), table_name='dim_operarios')
    op.drop_table('dim_operarios')
    op.drop_index(op.f('ix_dim_motivos_parada_tenant_id'), table_name='dim_motivos_parada')
    op.drop_table('dim_motivos_parada')
    # ### end Alembic commands ###
