"""agrega_tabla_tenants

Revision ID: c7bafc3c0de3
Revises: d820a37b3e0b
Create Date: 2026-05-25 22:29:33.603859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'c7bafc3c0de3'
down_revision: Union[str, None] = 'd820a37b3e0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants_saas',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('color_primario', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('locale_default', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_fact_paradas_programadas_tenant_id', table_name='fact_paradas_programadas')
    op.drop_table('fact_paradas_programadas')
    op.drop_index('ix_fact_asignaciones_matriz_tenant_id', table_name='fact_asignaciones_matriz')
    op.drop_table('fact_asignaciones_matriz')
    op.drop_index('ix_fact_asignaciones_supervisores_tenant_id', table_name='fact_asignaciones_supervisores')
    op.drop_table('fact_asignaciones_supervisores')
    op.alter_column('dim_estaciones', 'linea_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('ix_dim_supervisores_legajo'), 'dim_supervisores', ['legajo'], unique=False)
    op.alter_column('dim_turnos', 'linea_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dim_turnos', 'linea_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_dim_supervisores_legajo'), table_name='dim_supervisores')
    op.alter_column('dim_estaciones', 'linea_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_table('fact_asignaciones_supervisores',
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('linea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('turno_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('supervisor_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['linea_id'], ['dim_lineas.id'], name='fact_asignaciones_supervisores_linea_id_fkey'),
    sa.ForeignKeyConstraint(['supervisor_id'], ['dim_supervisores.id'], name='fact_asignaciones_supervisores_supervisor_id_fkey'),
    sa.ForeignKeyConstraint(['turno_id'], ['dim_turnos.id'], name='fact_asignaciones_supervisores_turno_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fact_asignaciones_supervisores_pkey'),
    sa.UniqueConstraint('tenant_id', 'fecha', 'linea_id', 'turno_id', name='uix_asignacion_supervisor_unica', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_fact_asignaciones_supervisores_tenant_id', 'fact_asignaciones_supervisores', ['tenant_id'], unique=False)
    op.create_table('fact_asignaciones_matriz',
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('fecha', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('linea_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('turno_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('estacion_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('operario_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['estacion_id'], ['dim_estaciones.id'], name='fact_asignaciones_matriz_estacion_id_fkey'),
    sa.ForeignKeyConstraint(['linea_id'], ['dim_lineas.id'], name='fact_asignaciones_matriz_linea_id_fkey'),
    sa.ForeignKeyConstraint(['operario_id'], ['dim_operarios.id'], name='fact_asignaciones_matriz_operario_id_fkey'),
    sa.ForeignKeyConstraint(['turno_id'], ['dim_turnos.id'], name='fact_asignaciones_matriz_turno_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fact_asignaciones_matriz_pkey'),
    sa.UniqueConstraint('tenant_id', 'fecha', 'linea_id', 'turno_id', 'estacion_id', name='uix_asignacion_matriz_unica', postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index('ix_fact_asignaciones_matriz_tenant_id', 'fact_asignaciones_matriz', ['tenant_id'], unique=False)
    op.create_table('fact_paradas_programadas',
    sa.Column('tenant_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('motivo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('fecha_inicio', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('fecha_fin', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('linea_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('turno_nombre', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hora_inicio', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.Column('hora_fin', postgresql.TIME(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['linea_id'], ['dim_lineas.id'], name='fact_paradas_programadas_linea_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='fact_paradas_programadas_pkey')
    )
    op.create_index('ix_fact_paradas_programadas_tenant_id', 'fact_paradas_programadas', ['tenant_id'], unique=False)
    op.drop_table('tenants_saas')
    # ### end Alembic commands ###
